spring:
  datasource:
    password: Zwarzony09871
    url: jdbc:mysql://localhost:3306/porspo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

